---
- hosts: localhost
  vars:
    jumphost_ip: 10.10.30.104
    rpi_nodes: 5
    rpi_update_inventory: true
  tasks:
    - name: Capturing DNSMasq DHCP Leases
      shell: cat /var/lib/misc/dnsmasq.leases | awk '{ print $4,$3,$2 }'
      register: _dnsmasq_dhcp_leases
      changed_when: false

    - name: Updating {{ inventory_dir }}
      template:
        src: hosts.inv.j2
        dest: "{{ inventory_dir }}/hosts.inv"
      delegate_to: localhost
      become: false
      when: rpi_update_inventory
