name: "Website Deployment"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan -no-color
        continue-on-error: true

      - name: "Terraform Apply"
        run:  terraform apply -auto-approve
  deploy:
    name: "Push to S3"
    runs-on: self-hosted
    needs: terraform
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup AWS CLI"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-east-1
      - name: "Sync files to S3 bucket"
        run: |
          aws s3 sync website/ s3://static.realewanderer.net --delete
