name: "Terraform Plan"

on:
  pull_request:

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: self-hosted
    defaults:
      run:
        working-directory: prod
    permissions:
      contents: read
      pull-requests: write
    env:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID  }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan -no-color
        continue-on-error: true
