name: "Terraform Destroy"

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: dev

jobs:
  terraform_build:
    name: "Terraform Proxmox Build"
    runs-on: self-hosted
    needs: snyk_sca
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
      PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
      TFVARS_B64: ${{ vars.TFVARS_B64 }}

    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - shell: bash
        run: |
          echo ${{ vars.TFVARS_B64 }} | base64 -d > terraform.tfvars

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan -no-color
        continue-on-error: true

      - name: "Terraform Destroy"
        run: terraform destroy --auto-approve

