name: "IaC Deployment"

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: prod
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  # Runs Snyk for SCA (Software Composition Analysis) in IaC
  snyk_sca:
    name: "Snyk SCA Scan"
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check manifest file for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --report
        continue-on-error: true

  # Runs Terraform to build out AWS infrastructure and DNS rules
  terraform_build:
    name: "Terraform AWS Build"
    runs-on: self-hosted
    needs: snyk_sca
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
      AWS_REGION: us-east-1
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DOMAIN: ${{ vars.TF_SITE_DOMAIN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan -var="site_domain=$DOMAIN" -no-color
        continue-on-error: true

      - name: "Terraform Apply"
        run:  terraform apply -var="site_domain=$DOMAIN" -auto-approve
